"""add expense

Revision ID: 17eec1603212
Revises: 6a78932972df
Create Date: 2020-02-01 19:51:37.201303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17eec1603212'
down_revision = '6a78932972df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    # ### end Alembic commands ###
