"""person table

Revision ID: 6a78932972df
Revises: 5cfbc24d4c16
Create Date: 2020-01-31 16:22:52.033147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a78932972df'
down_revision = '5cfbc24d4c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('kisse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kisse_id'], ['kisse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
